using System.ComponentModel;
using System.Text.Json;
using ModelContextProtocol.Server;
using MechCue;

[McpServerToolType]
public static class SolidEdgeCadTools
{
    static Task<string> Execute(string operation, Func<object> action) => SolidEdgeTools.ExecuteCad(operation, action);
    [McpServerTool, Description("Create and activate a new part, assembly or draft. Parts use Ordered mode. Optional absolute templatePath must match the document type. Does not save or close existing documents. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_new_document(string kind, string templatePath = "") => Execute("new-document", () => Bridge.CadNew(kind, templatePath));
    [McpServerTool, Description("Open and activate an existing .par/.asm/.dft/.psm using an absolute path. Does not close or save existing documents. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_open_document(string filePath) => Execute("open-document", () => Bridge.CadOpen(filePath));
    [McpServerTool, Description("Explicitly save the active document matched by expectedDocument. For new files supply an absolute outputPath in an existing folder; never overwrites another file. Empty outputPath saves the current existing file. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_save_document(string expectedDocument, string outputPath = "") => Execute("save-document", () => Bridge.CadSave(expectedDocument, outputPath));
    [McpServerTool(ReadOnly = true), Description("List reference planes with 1-based numbers and native names. For an assembly supply partNumber to read a component without activating its document. Plane-local XY coordinates depend on the selected plane; read before creating a profile. Requires Read/select or Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_list_planes(string expectedDocument, int partNumber = 0) => SolidEdgeTools.ExecuteCad("list-planes", () => Bridge.CadListPlanes(expectedDocument, partNumber), false);
    [McpServerTool(ReadOnly = true), Description("List a part's feature tree and modeling mode (Ordered=2). Requires Read/select or Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_list_features(string expectedDocument) => SolidEdgeTools.ExecuteCad("list-features", () => Bridge.CadListFeatures(expectedDocument), false);
    [McpServerTool, Description("Create an Ordered extrusion or finite cut. shape=rectangle/circle/polygon; operation=add/cut; direction=positive/negative/symmetric relative to plane normal. All lengths mm, profile origin is plane-local XY. Polygon pointsJson is [{\"x\":0,\"y\":0},...], 3-256 distinct vertices without repeated end; ignores origin. First additive feature creates the solid, later adds must touch it. Cut requires an existing solid. Single-body parts only. Geometry remains unsaved; no automatic undo. Failed COM operations may leave partial geometry; inspect the feature list. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_extrude_profile(string expectedDocument, string shape, double depthMm, double widthMm = 0, double heightMm = 0, double radiusMm = 0, int planeNumber = 1, double xMm = 0, double yMm = 0, string operation = "add", string direction = "positive", string pointsJson = "", string featureName = "")
        => Execute("extrude", () => Bridge.CadExtrude(expectedDocument, shape, widthMm, heightMm, radiusMm, depthMm, planeNumber, xMm, yMm, operation, direction, pointsJson, featureName));
    [McpServerTool, Description("Add a saved part/subassembly to the active assembly. Absolute XYZ in mm, rotations in degrees applied Rx then Ry then Rz. ground=true adds a fixed relationship; use false for parts to constrain. No automatic save. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_place_part(string expectedDocument, string filePath, double xMm = 0, double yMm = 0, double zMm = 0, double rxDeg = 0, double ryDeg = 0, double rzDeg = 0, bool ground = true)
        => Execute("place-part", () => Bridge.CadPlacePart(expectedDocument, filePath, xMm, yMm, zMm, rxDeg, ryDeg, rzDeg, ground));
    [McpServerTool, Description("Set a top-level occurrence's absolute XYZ mm and Rx/Ry/Rz degree pose. Existing assembly constraints may prevent the pose; the result is checked, but this is not an atomic rollback. No automatic save. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_position_part(string expectedDocument, int partNumber, double xMm, double yMm, double zMm, double rxDeg = 0, double ryDeg = 0, double rzDeg = 0)
        => Execute("position-part", () => Bridge.CadPositionPart(expectedDocument, partNumber, xMm, yMm, zMm, rxDeg, ryDeg, rzDeg));
    [McpServerTool, Description("Constrain two different top-level occurrences using their reference planes. Read each component's planes first. normalsAligned=false mates opposite normals; true aligns them. offsetMm is a native signed plane offset. Ground only the base part; overconstraints can fail. No automatic save or rollback. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_mate_planes(string expectedDocument, int partA, int planeA, int partB, int planeB, bool normalsAligned = false, double offsetMm = 0)
        => Execute("mate-planes", () => Bridge.CadMatePlanes(expectedDocument, partA, planeA, partB, planeB, normalsAligned, offsetMm));
    [McpServerTool, Description("Add a drawing view on the active draft sheet from an existing saved .par/.psm/.asm. orientation=front/top/right/left/back/bottom/isometric; scale=1 means 1:1. Sheet positions xMm/yMm use mm. Reuses model links. Does not add manufacturing dimensions, tolerances or save the draft. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_add_drawing_view(string expectedDocument, string modelPath, string orientation, double scale, double xMm, double yMm)
        => Execute("drawing-view", () => Bridge.CadAddDrawingView(expectedDocument, modelPath, orientation, scale, xMm, yMm));
    [McpServerTool, Description("Update all drawing views in the active draft from their linked models. Does not save. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_update_drawing(string expectedDocument) => Execute("update-drawing", () => Bridge.CadUpdateDrawing(expectedDocument));
    [McpServerTool, Description("Export the active draft as PDF to a new absolute outputPath; existing files are rejected. Output folder must exist. Requires Creation/edit mode in MechCue MCP tray settings.")]
    public static Task<string> solidedge_export_pdf(string expectedDocument, string outputPath) => Execute("export-pdf", () => Bridge.CadExportPdf(expectedDocument, outputPath));
    [McpServerTool(ReadOnly=true), Description("Propose front direction and third-angle views for the active saved 3D model, or an existing draft's linked model. modelPath required only for drafts with multiple links. frontOrientation=auto/front/back/top/bottom/right/left. Auto preserves an existing orthographic view, then uses concept axes, cylindrical feature normals or largest bounding projection. Does not modify CAD. Proposal is geometric, not manufacturing intent.")]
    public static Task<string> solidedge_plan_drawing(string expectedDocument,string modelPath="",string frontOrientation="auto",bool includeIsometric=true) => SolidEdgeTools.ExecuteCad("plan-drawing",()=>Bridge.CadPlanDrawing(expectedDocument,modelPath,frontOrientation,includeIsometric),false);
    [McpServerTool(ReadOnly=true), Description("List active-sheet drawing views, orientation, scale, model links, ranges, edge counts and dimension count. Does not modify CAD.")]
    public static Task<string> solidedge_list_drawing_views(string expectedDocument) => SolidEdgeTools.ExecuteCad("list-drawing-views",()=>Bridge.CadListDrawingViews(expectedDocument),false);
    [McpServerTool, Description("Create and save a new dimensioned concept draft from the active SAVED, unmodified 3D model. outputPath absolute .dft, existing files rejected. Optional draft template; A3 or larger recommended. frontOrientation=auto/front/back/top/bottom/right/left. Third-angle front/up/right projections and optional isometric, fitted metric scale. dimensionMode=features/overall/none. Associated reference dimensions include three extents and visible circles with center positions; warnings report unsupported dimensions. No sections or tolerances. Does not save/modify source model. Partial draft remains open on failure. Requires Creation/edit mode.")]
    public static Task<string> solidedge_auto_drawing(string expectedDocument,string outputPath,string templatePath="",string frontOrientation="auto",bool includeIsometric=true,string dimensionMode="features") => Execute("auto-drawing",()=>Bridge.CadAutoDrawing(expectedDocument,outputPath,templatePath,frontOrientation,includeIsometric,dimensionMode));
    [McpServerTool, Description("Add associated overall and circular-feature reference dimensions to one orthographic view on the active sheet. viewNumber 1-based from list_drawing_views. dimensionMode=overall/features; maxDimensions=1..30. Existing MechCue-generated dimensions are not duplicated. Does not save. Read warnings for skipped/unsupported dimensions; no tolerances or sections. Requires Creation/edit mode.")]
    public static Task<string> solidedge_dimension_drawing_view(string expectedDocument,int viewNumber,string dimensionMode="features",int maxDimensions=12) => Execute("dimension-drawing-view",()=>Bridge.CadDimensionDrawingView(expectedDocument,viewNumber,dimensionMode,maxDimensions));    [McpServerTool, Description("Complete an existing draft's active sheet from a chosen standard orthographic frontViewNumber (1-based): reuse or add top/right connected third-angle projections and optional isometric for that same linked model, then add associated dimensions. dimensionMode=features/overall/none. Keeps existing layout; warnings report border overflows. Existing views and MechCue dimensions are not duplicated. Does not save or modify the 3D model. Requires Creation/edit mode.")]
    public static Task<string> solidedge_complete_drawing(string expectedDocument,int frontViewNumber=1,bool includeIsometric=true,string dimensionMode="features") => Execute("complete-drawing",()=>Bridge.CadCompleteDrawing(expectedDocument,frontViewNumber,includeIsometric,dimensionMode));    [McpServerTool, Description("Rearrange existing MechCue-generated linear dimensions, smallest nearest the geometry and largest outermost, independently below and left of each view. viewNumber=0 means all active-sheet views. Also removes duplicate MechCue circular-feature position dimensions measuring the same projected interval in the same view and axis. Reports removedDuplicates. Equal values with different datums/directions, radial callouts and user-created dimensions are retained. Ambiguous legacy ownership is skipped with warnings. Does not add dimensions or save. Requires Creation/edit mode.")]
    public static Task<string> solidedge_arrange_drawing_dimensions(string expectedDocument,int viewNumber=0) => Execute("arrange-drawing-dimensions",()=>Bridge.CadArrangeDrawingDimensions(expectedDocument,viewNumber));
    [McpServerTool(ReadOnly=true), Description("List design-state PMI dimensions and model views in the active single-body .par part. Values are native metres or radians; reports constraint, visibility, status and MechCue metadata. Does not change geometry or save. First native access can initialize the PMI container and mark the document dirty; nativePmiInitialized reports this.")]
    public static Task<string> solidedge_list_pmi(string expectedDocument) => SolidEdgeTools.ExecuteCad("list-pmi",()=>Bridge.CadListPmi(expectedDocument),false);
    [McpServerTool, Description("Add associated reference PMI dimensions directly to the active single-body .par part without changing solid geometry. dimensionMode=features/overall; maxDimensions=3..100 limits newly added dimensions. Uses global orthogonal planes. Features include axis extents, circular-edge diameters/positions, orthogonal steps and supported coplanar inclination angles. Optional named MechCue PMI XY/XZ/YZ model views group dimensions by plane. Preserves user PMI and avoids repeating generated IDs. Failed dimension creation is reported in warnings; unsupported geometry is skipped. No inferred tolerances or datums, no auto-save; review then save explicitly. Requires Creation/edit mode.")]
    public static Task<string> solidedge_auto_pmi(string expectedDocument,string dimensionMode="features",int maxDimensions=30,bool createModelViews=true) => Execute("auto-pmi",()=>Bridge.CadAutoPmi(expectedDocument,dimensionMode,maxDimensions,createModelViews));
    [McpServerTool, Description("Apply an existing PMI model view by its exact name from solidedge_list_pmi, changing the 3D view and visible annotations. Active single-body .par part only. Does not save. Requires Creation/edit mode.")]
    public static Task<string> solidedge_show_pmi_view(string expectedDocument,string viewName) => Execute("show-pmi-view",()=>Bridge.CadShowPmiView(expectedDocument,viewName));
}
