using System.ComponentModel;
using ModelContextProtocol.Server;
using MechCue;

[McpServerToolType]
public static class MachiningTools
{
    [McpServerTool(ReadOnly=true),Description("List exact metric straight thread descriptions and diameters from Solid Edge's configured legacy HoleSizeFile (.txt). Requires CAD read permission. Not the newer XLSX standards catalog. Use descriptions exactly; tap drill diameter is selected by caller within native minor/nominal bounds.")]
    public static Task<string> solidedge_list_metric_threads()=>SolidEdgeTools.ExecuteCad("list-metric-threads",()=>Bridge.CadListMetricThreads(),false);
    [McpServerTool,Description("Create a native Ordered Hole feature in a single-model .par. centersJson=[{x,y}] in plane-local mm, exactly ONE center; use pattern_hole for repeats. holeType regular/counterbore/countersink; extent through (one direction) or finite with depthMm. planeOffsetMm offsets selected plane along its normal; choose entry surface and direction positive/negative into solid. Countersink angle is degrees. Optional exact metric threadDescription from list_metric_threads creates native tapped-hole data; diameterMm is caller-selected tap drill diameter within native internal minor/nominal bounds. Uses configured legacy hole-size table. threadDepthMm=0 full hole extent, positive finite thread depth. Cosmetic internal threads only; no helical solid or external screw threads. Rejects unknown sizes; checks retained dimensions and all feature health, attempts cleanup on failure. Does not save.")]
    public static Task<string> solidedge_create_hole(string expectedDocument,string centersJson,double diameterMm,string holeType="regular",string extent="through",double depthMm=0,int planeNumber=1,double planeOffsetMm=0,string direction="positive",double counterboreDiameterMm=0,double counterboreDepthMm=0,double countersinkDiameterMm=0,double countersinkAngleDeg=90,string threadDescription="",double threadDepthMm=0,string featureName="")
        =>SolidEdgeTools.ExecuteCad("create-hole",()=>Bridge.CadCreateHole(expectedDocument,centersJson,diameterMm,holeType,extent,depthMm,planeNumber,planeOffsetMm,direction,counterboreDiameterMm,counterboreDepthMm,countersinkDiameterMm,countersinkAngleDeg,threadDescription,threadDepthMm,featureName));
    [McpServerTool(ReadOnly=true),Description("Read native Ordered Hole feature data: diameters/depths in mm, counterbore/countersink, native thread description/treatment/depth, extent and center count. Cutouts are not reported as holes; pattern instances are represented by their native Pattern feature.")]
    public static Task<string> solidedge_list_holes(string expectedDocument)=>SolidEdgeTools.ExecuteCad("list-holes",()=>Bridge.CadListHoles(expectedDocument),false);
    [McpServerTool,Description("Create native rectangular/circular Pattern from one named native Hole containing one center. 2..256 total instances including seed; uses Solid Edge fixed spacing. Rectangular X/Y axes are selected reference-plane axes; rectangleAngleDeg rotation. Circular axis centerX/Y/Zmm is in document 3D coordinates, angleSpacingDeg positive, right curve direction; avoid duplicate 360-degree endpoint. Includes native seed feature dependency. Checks all feature health, attempts removal of only new patterns on failure. Does not save.")]
    public static Task<string> solidedge_pattern_hole(string expectedDocument,string sourceFeatureName,string patternType="rectangular",int xCount=2,int yCount=2,double xSpacingMm=20,double ySpacingMm=20,int radialCount=4,double angleSpacingDeg=90,int planeNumber=1,double centerXmm=0,double centerYmm=0,double centerZmm=0,double rectangleAngleDeg=0,string featureName="")
        =>SolidEdgeTools.ExecuteCad("pattern-hole",()=>Bridge.CadPatternHole(expectedDocument,sourceFeatureName,patternType,xCount,yCount,xSpacingMm,ySpacingMm,radialCount,angleSpacingDeg,planeNumber,centerXmm,centerYmm,centerZmm,rectangleAngleDeg,featureName));
    [McpServerTool,Description("Create native equal-setback (45-degree) Chamfer on explicit current edgeIdsJson from list_edges, 1..256 unique keys; setbackMm positive. Ordered single-model part. Validates keys before mutation; checks features and removes newly added chamfers on failure. No save. Re-read topology keys after edits.")]
    public static Task<string> solidedge_chamfer_edges(string expectedDocument,string edgeIdsJson,double setbackMm,string featureName="")=>SolidEdgeTools.ExecuteCad("chamfer-edges",()=>Bridge.CadChamferEdges(expectedDocument,edgeIdsJson,setbackMm,featureName));
    [McpServerTool(ReadOnly=true),Description("Read a named feature's sketch dimensions, driving flag, type and native variableName. Linear dimensions including circle diameters are in mm. Use on rectangle/circle extrusions created with drivingDimensions=true; not PMI reference annotations.")]
    public static Task<string> solidedge_list_profile_dimensions(string expectedDocument,string featureName)=>SolidEdgeTools.ExecuteCad("list-profile-dimensions",()=>Bridge.CadListProfileDimensions(expectedDocument,featureName),false);
    [McpServerTool,Description("Edit one named driving sketch dimension using exact variableName from list_profile_dimensions; valueMm positive. Intended for rectangle widths/heights and circle diameters. Recomputes, checks all features and requested value, attempts restore on failure. Does not save. Re-read edge/face IDs after change.")]
    public static Task<string> solidedge_set_profile_dimension(string expectedDocument,string featureName,string variableName,double valueMm)=>SolidEdgeTools.ExecuteCad("set-profile-dimension",()=>Bridge.CadSetProfileDimension(expectedDocument,featureName,variableName,valueMm));
}
