using MechCue;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Server;
if(McpUpdate.Updating()) return;
McpAccessSettings.StartTray();
var builder=Host.CreateApplicationBuilder(args.Where(a=>a is not ("--allow-solidedge" or "--allow-solidedge-write")).ToArray());
builder.Logging.ClearProviders();builder.Logging.AddConsole(o=>o.LogToStandardErrorThreshold=LogLevel.Trace);
var traffic = new McpTrafficJournal();
builder.Services.AddMcpServer().WithStreamServerTransport(new McpTrafficStream(Console.OpenStandardInput(), traffic, "in"), new McpTrafficStream(Console.OpenStandardOutput(), traffic, "out")).WithToolsFromAssembly();
using var host=builder.Build();
using var shutdown=new McpShutdownSignal(()=>host.Services.GetRequiredService<IHostApplicationLifetime>().StopApplication());
await host.RunAsync();
