using System.ComponentModel;
using ModelContextProtocol.Server;
using MechCue;

[McpServerToolType]
public static class SolidEdgeSimulationTools
{
    [McpServerTool(ReadOnly=true),Description("List current single-solid .par faces with reference-key faceIds, area mm2, bounds mm and analytic plane normals. Requires expectedDocument. Use faceIds for simulation conditions; re-read after geometry edits. Does not modify CAD.")]
    public static Task<string> solidedge_list_simulation_faces(string expectedDocument)=>SolidEdgeTools.ExecuteCad("simulation-faces",()=>Bridge.CadListSimulationFaces(expectedDocument),false);
    [McpServerTool,Description("Highlight faces using faceIdsJson (JSON array from list_simulation_faces). Replaces Solid Edge selection without changing geometry. Requires Read/select or Creation/edit mode.")]
    public static Task<string> solidedge_select_simulation_faces(string expectedDocument,string faceIdsJson)=>SolidEdgeTools.ExecuteCad("simulation-select",()=>Bridge.CadSelectSimulationFaces(expectedDocument,faceIdsJson),false);
    [McpServerTool(ReadOnly=true),Description("List native simulation studies with 1-based studyNumber, mesh settings, loads, constraints, face IDs and solved/error status, plus current material properties. Single-solid .par only. Does not save or solve. Missing API fields appear in warnings.")]
    public static Task<string> solidedge_list_simulation_studies(string expectedDocument)=>SolidEdgeTools.ExecuteCad("simulation-studies",()=>Bridge.CadListSimulationStudies(expectedDocument),false);
    [McpServerTool(ReadOnly=true),Description("List Solid Edge material libraries and exact material names; libraryName empty uses the first installed library, or pass a library returned by this tool. Returns current document material with native SI mechanical properties. Single-solid .par only.")]
    public static Task<string> solidedge_list_simulation_materials(string expectedDocument,string libraryName="")=>SolidEdgeTools.ExecuteCad("simulation-materials",()=>Bridge.CadListSimulationMaterials(expectedDocument,libraryName),false);
    [McpServerTool,Description("Apply an exact Solid Edge library material to the active single-solid .par. Use list_simulation_materials first. Empty libraryName uses first installed library. Changes document material, not the shared library; does not save. Requires Creation/edit mode.")]
    public static Task<string> solidedge_apply_simulation_material(string expectedDocument,string materialName,string libraryName="")=>SolidEdgeTools.ExecuteCad("simulation-material",()=>Bridge.CadApplySimulationMaterial(expectedDocument,materialName,libraryName));
    [McpServerTool,Description("Create a NEW native linear static tetrahedral study for the complete single solid .par body. Defaults to native meshLevel=5; slider levels 1..10 (1 coarse, 10 fine) automatically compute size from part geometry. Optional positive meshSizeMm=0.1..1000 overrides the slider with an absolute size. Existing studies remain. Close the Simulation Results environment before creating a study. Returns native name and 1-based studyNumber. Does not assign material, solve or save; failed native operations may leave a partial study. Requires Creation/edit mode and Simulation availability.")]
    public static Task<string> solidedge_create_simulation_study(string expectedDocument,double meshSizeMm=0,int meshLevel=5)=>SolidEdgeTools.ExecuteCad("simulation-create",()=>Bridge.CadCreateSimulationStudy(expectedDocument,meshSizeMm,meshLevel));
    [McpServerTool,Description("Add a fully fixed face condition to the specified linear static solid study. faceIdsJson is a JSON array from the face list; [] uses currently selected faces, rejecting other objects. Optional native condition name. Does not save; results may become outdated. Requires Creation/edit mode.")]
    public static Task<string> solidedge_add_simulation_fixed(string expectedDocument,int studyNumber,string faceIdsJson="[]",string name="")=>SolidEdgeTools.ExecuteCad("simulation-fixed",()=>Bridge.CadAddSimulationFixed(expectedDocument,studyNumber,faceIdsJson,name));
    [McpServerTool,Description("Add a face load: kind=force (positive total N along normalized global XYZ vector) or pressure (positive MPa along native face-normal pressure convention; vector ignored). faceIdsJson JSON array from face list, or [] for selected faces. Multiple-face force distribution follows Solid Edge. Optional native name. No save or solve. Requires Creation/edit mode.")]
    public static Task<string> solidedge_add_simulation_load(string expectedDocument,int studyNumber,string kind,double value,double directionX=0,double directionY=0,double directionZ=-1,string faceIdsJson="[]",string name="")=>SolidEdgeTools.ExecuteCad("simulation-load",()=>Bridge.CadAddSimulationLoad(expectedDocument,studyNumber,kind,value,directionX,directionY,directionZ,faceIdsJson,name));
    [McpServerTool,Description("Mesh and solve a single-solid linear static study, or mesh only with meshOnly=true. Optional meshLevel=1..10 matches the native coarseness slider (default creation level 5); 0 keeps current sizing. Or meshSizeMm=0.1..1000 sets absolute size; both 0 keep current settings. Do not pass both positive meshLevel and meshSizeMm. regenerateMesh=true removes and rebuilds only this study mesh; needed to apply a changed size to an existing mesh. suppressAlerts=true suppresses native alerts for this call and restores the previous DisplayAlerts value in finally, even on error. Solving requires assigned elastic material plus active constraints/loads. Solid Edge solver/license dialogs may require attention. completed is native status, never assume success from launch. No automatic retry/save; call list_simulation_studies to check later. Stores an input verification fingerprint in the part on successful solve; close Results before switching studies. Requires Creation/edit mode and appropriate Simulation license.")]
    public static Task<string> solidedge_run_simulation(string expectedDocument,int studyNumber,bool meshOnly=false,double meshSizeMm=0,bool suppressAlerts=false,bool regenerateMesh=false,int meshLevel=0)=>SolidEdgeTools.ExecuteCad("simulation-run",()=>Bridge.CadRunSimulation(expectedDocument,studyNumber,meshOnly,meshSizeMm,suppressAlerts,regenerateMesh,meshLevel));
    [McpServerTool(ReadOnly=true),Description("Read solved study extrema: resultKind=stress (solid von Mises, MPa), displacement (total translation, mm), or active (current native plot, returned with type and units). Locations mm; native SI values retained. Requires a verified MechCue solve with unchanged geometry, material, conditions and mesh settings; rejects unverified/stale results even when native IsSolved is true. Does not change plot selection or save.")]
    public static Task<string> solidedge_get_simulation_results(string expectedDocument,int studyNumber,string resultKind="stress")=>SolidEdgeTools.ExecuteCad("simulation-results",()=>Bridge.CadGetSimulationResults(expectedDocument,studyNumber,resultKind),false);
    [McpServerTool,Description("Activate a solved linear static study and show resultKind=stress/displacement/active in Solid Edge. Returns the requested plot extrema. Does not save. Requires Creation/edit mode.")]
    public static Task<string> solidedge_show_simulation_results(string expectedDocument,int studyNumber,string resultKind="stress")=>SolidEdgeTools.ExecuteCad("simulation-show",()=>Bridge.CadShowSimulationResults(expectedDocument,studyNumber,resultKind));
}
