namespace MechCue;
public static class HostCommands
{
    public static HostAction[] RibbonActions => Enum.GetValues<HostAction>().Where(a => a != HostAction.Stop).ToArray();
    public static string Caption(HostAction action) => UiText.Text(action switch {
        (HostAction)1 => "タイムチャート",
        (HostAction)2 => "再生 / 一時停止",
        (HostAction)3 => "停止",
        (HostAction)4 => "最大化",
        (HostAction)5 => "最小化",
        (HostAction)6 => "最小表示",
        (HostAction)7 => "CAD保存",
        (HostAction)8 => "接続",
        (HostAction)9 => "切断",
        (HostAction)10 => "基準に戻す",
        (HostAction)11 => "JSON読込",
        (HostAction)12 => "JSON保存",
        (HostAction)13 => "表出力",
        (HostAction)14 => "表読込",
        (HostAction)15 => "反映",
        (HostAction)16 => "干渉",
        (HostAction)17 => "反復",
        (HostAction)18 => "重ねて表示",
        (HostAction)19 => "編集",
        (HostAction)20 => "動作確認",
        (HostAction)21 => "元に戻す",
        (HostAction)22 => "使い方",
        (HostAction)23 => "機構追加",
        (HostAction)24 => "更新",
        (HostAction)25 => "選択部品",
        (HostAction)26 => "全候補",
        (HostAction)27 => "現在値",
        (HostAction)28 => "強調",
        (HostAction)29 => "登録・変更",
        (HostAction)30 => "割り当て解除",
        (HostAction)31 => "往復動作",
        (HostAction)32 => "AI接続",
        (HostAction)33 => "機構一覧",
        (HostAction)34 => "選択中の設定",
        (HostAction)35 => "数値編集",
        _ => "MechCue" });
    public static bool IsToggle(HostAction action) => action is HostAction.Apply or HostAction.Collision or HostAction.Loop or HostAction.Overlay or HostAction.Edit or HostAction.Review or HostAction.Ai or HostAction.TracksPanel or HostAction.SettingsPanel or HostAction.PointsPanel;
    public static string Hint(HostAction action) => action switch {
        HostAction.Play => UiText.IsJapanese ? "再生と一時停止を切り替えます。現在の時刻から再開します。" : "Toggle playback and pause; resume from the current time.",
        HostAction.Apply => UiText.IsJapanese ? "Solid Edgeへの反映を切り替えます。" : "Toggle applying values to Solid Edge.",
        HostAction.Collision => UiText.IsJapanese ? "干渉したら停止する設定を切り替えます。" : "Toggle stopping on interference.",
        HostAction.Ai => UiText.IsJapanese ? "AIからの接続を切り替えます。標準はオンです。" : "Toggle AI access; enabled by default.",
        HostAction.TracksPanel or HostAction.SettingsPanel or HostAction.PointsPanel => UiText.IsJapanese ? "パネルの表示と非表示を切り替えます。" : "Show or hide this panel.",
        HostAction.Compact => UiText.CommandHint("最小表示"), HostAction.Save => UiText.CommandHint("CADに保存"),
        HostAction.JsonOpen => UiText.CommandHint("開く"), HostAction.JsonSave => UiText.CommandHint("保存"),
        HostAction.TableExport => UiText.CommandHint("表を書き出し"), HostAction.TableImport => UiText.CommandHint("表を読み込み"),
        _ => Caption(action)
    };
    public static string Group(HostAction action) => UiText.Text(action switch {
        (HostAction)1 => "表示",
        (HostAction)2 => "再生",
        (HostAction)3 => "再生",
        (HostAction)4 => "表示",
        (HostAction)5 => "表示",
        (HostAction)6 => "表示",
        (HostAction)7 => "データ",
        (HostAction)8 => "接続操作",
        (HostAction)9 => "接続操作",
        (HostAction)10 => "接続操作",
        (HostAction)11 => "データ",
        (HostAction)12 => "データ",
        (HostAction)13 => "データ",
        (HostAction)14 => "データ",
        (HostAction)15 => "再生",
        (HostAction)16 => "再生",
        (HostAction)17 => "再生",
        (HostAction)18 => "表示",
        (HostAction)19 => "編集",
        (HostAction)20 => "編集",
        (HostAction)21 => "編集",
        (HostAction)22 => "表示",
        (HostAction)23 => "機構",
        (HostAction)24 => "機構",
        (HostAction)25 => "機構",
        (HostAction)26 => "機構",
        (HostAction)27 => "機構",
        (HostAction)28 => "機構",
        (HostAction)29 => "機構",
        (HostAction)30 => "機構",
        (HostAction)31 => "機構",
        (HostAction)32 => "接続操作",
        (HostAction)33 => "表示",
        (HostAction)34 => "表示",
        (HostAction)35 => "表示",
        _ => "表示" });
}
